# Generated by Django 5.1.4 on 2024-12-18 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=233)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DRAFT', 'DRAFT'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], max_length=150)),
                ('category_type', models.CharField(choices=[('HEALTH', 'HEALTH'), ('EDUCATION', 'EDUCATION'), ('TECHNOLOGY', 'TECHNOLOGY')], max_length=150)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('raised_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reward', models.TextField()),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('PENDING', 'PENDING'), ('REJECTED', 'REJECTED')], max_length=17)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='projects/videos/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, to='campaign.category')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign')),
            ],
        ),
    ]
